// Generated by CoffeeScript 1.12.6

/*
 * Spec helper
 */

(function() {
  'use strict';
  var SpecHelper;

  SpecHelper = function() {
    return true;
  };

  SpecHelper.prototype.f = function() {
    return 1;
  };

  SpecHelper.prototype.forMocha = function() {
    return typeof describe === 'function';
  };

  module.exports = SpecHelper;

}).call(this);
