// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        matcher: 'plain',
        it: 'really makes a test!',
        i: void 0,
        e: void 0
      }
    ]);
  };

}).call(this);
