// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.context('With ddry hooks', function() {
      return dd.drive([
        {
          before: function() {
            return this.container = 'abc';
          },
          it: "wraps '1'",
          i: [1],
          e: 'abc|1|',
          after: function() {
            return this.container += 'xyz';
          }
        }, {
          before: function() {
            return this.container += 'abc';
          },
          after: function() {
            return this.container += 'xyz';
          }
        }, {
          it: "wraps '1' again",
          i: [2],
          e: 'abc|1|xyzabc|2|'
        }, {
          it: "wraps '1' again and again",
          i: [3],
          e: 'abc|1|xyzabc|2|xyzabc|3|',
          after: function() {
            return delete this.container;
          }
        }
      ]);
    });
  };

}).call(this);
